# Generated by Django 5.2.8 on 2025-11-16 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formulario', models.TextField(max_length=100)),
                ('genero_formulario', models.TextField(max_length=20)),
                ('edad_formulario', models.IntegerField()),
                ('ant_formulario', models.TextField(blank=True, max_length=200)),
                ('alergia_formulario', models.TextField(blank=True, max_length=200)),
                ('motivo_formulario', models.TextField()),
                ('presion_formulario', models.TextField(blank=True, max_length=20)),
                ('pulso_formulario', models.TextField(blank=True, max_length=20)),
                ('temperatura_formulario', models.TextField(blank=True, max_length=20)),
                ('saturacion_formulario', models.TextField(blank=True, max_length=20)),
                ('fecha_envio_formulario', models.DateTimeField(auto_now_add=True)),
                ('observaciones_formulario', models.TextField(blank=True)),
                ('prioridad_formulario', models.TextField(blank=True, max_length=20)),
                ('preparacion_formulario', models.TextField(blank=True, max_length=20)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='evidencias/')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urgencias.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usuario', models.EmailField(max_length=100, unique=True)),
                ('password_usuario', models.TextField(max_length=20)),
                ('cargo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urgencias.cargo')),
            ],
        ),
    ]
