# Generated by Django 5.2.8 on 2025-11-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='diagnostico',
            new_name='diagnostico_formulario',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='tratamiento',
            new_name='tratamiento_formulario',
        ),
    ]
