# Generated by Django 5.2.8 on 2025-11-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0002_rename_diagnostico_formulario_diagnostico_formulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='imagen_formulario',
            field=models.FileField(blank=True, null=True, upload_to='formularios/'),
        ),
        migrations.DeleteModel(
            name='Evidencia',
        ),
    ]
