# Generated by Django 5.2.8 on 2025-11-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0003_formulario_imagen_formulario_delete_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='fecha_envio_formulario',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='motivo_formulario',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='alergia_formulario',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='ant_formulario',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='diagnostico_formulario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='observaciones_formulario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='preparacion_formulario',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='presion_formulario',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='prioridad_formulario',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='pulso_formulario',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='saturacion_formulario',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='temperatura_formulario',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tratamiento_formulario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
