# Generated by Django 5.2.8 on 2025-11-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0004_remove_formulario_fecha_envio_formulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='fecha_envio_formulario',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='motivo_formulario',
            field=models.TextField(null=True),
        ),
    ]
