# Generated by Django 5.2.8 on 2025-11-17 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0005_formulario_fecha_envio_formulario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='imagen_formulario',
        ),
        migrations.AddField(
            model_name='formulario',
            name='enfermera_formulario',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tens_formulario',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urgencias.formulario')),
            ],
        ),
    ]
