# Generated by Django 5.2.8 on 2025-11-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0006_remove_formulario_imagen_formulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
