# Generated by Django 5.2.8 on 2025-11-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0007_usuario_apellido_usuario_usuario_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='estado_formulario',
            field=models.TextField(default='Enviado', max_length=20),
        ),
    ]
