# Generated by Django 5.2.8 on 2025-11-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0008_formulario_estado_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='estado_formulario',
            field=models.TextField(default='Recibido', max_length=20),
        ),
    ]
