# Generated by Django 5.2.8 on 2025-11-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0009_alter_formulario_estado_formulario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='tens_formulario',
            new_name='paramedico_formulario',
        ),
    ]
